#Build image use golang offical image
FROM golang:alpine3.22 AS builder

#Incase of dependency needs
RUN apk add --no-cache git

WORKDIR /app

#Copy Dependencies (Caches so no redownloading each time)
COPY go.mod go.sum ./
#Then download libraries
RUN go mod download

#Copy Source Code
COPY . .

#Build binary CGO_ENABLE=0 createss a static binary
RUN CGO_ENABLED=0 GOOS=linux go build -o bitmesh-gateway .

FROM alpine:latest

#Non root user (no password)
RUN adduser -D bitmesh

#Certificates
RUN apk --no-cache add ca-certificates

WORKDIR /home/bitmesh

#Copy the binary
COPY --from=builder /app/bitmesh-gateway .

#Needed for config
COPY ./internal/config/config.yaml .

#Give new user permission to binary and config
RUN chown bitmesh:bitmesh bitmesh-gateway config.yaml

#Switch User
USER bitmesh

#Expose Port (internal port map also 50000)
EXPOSE 50000

CMD [ "./bitmesh-gateway" ]