// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/proto/gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureFlags  uint32                 `protobuf:"varint,1,opt,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_api_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *RouteRequest) GetFeatureFlags() uint32 {
	if x != nil {
		return x.FeatureFlags
	}
	return 0
}

func (x *RouteRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetService string                 `protobuf:"bytes,1,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	Allowed       bool                   `protobuf:"varint,2,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_api_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *RouteResponse) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *RouteResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_api_proto_gateway_proto protoreflect.FileDescriptor

const file_api_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/gateway.proto\x12\agateway\"M\n" +
	"\fRouteRequest\x12#\n" +
	"\rfeature_flags\x18\x01 \x01(\rR\ffeatureFlags\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"P\n" +
	"\rRouteResponse\x12%\n" +
	"\x0etarget_service\x18\x01 \x01(\tR\rtargetService\x12\x18\n" +
	"\aallowed\x18\x02 \x01(\bR\aallowed2N\n" +
	"\rGatewayRouter\x12=\n" +
	"\fRouteMessage\x12\x15.gateway.RouteRequest\x1a\x16.gateway.RouteResponseB.Z,github.com/WillDomine/bitmesh-gateway/api/pbb\x06proto3"

var (
	file_api_proto_gateway_proto_rawDescOnce sync.Once
	file_api_proto_gateway_proto_rawDescData []byte
)

func file_api_proto_gateway_proto_rawDescGZIP() []byte {
	file_api_proto_gateway_proto_rawDescOnce.Do(func() {
		file_api_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_gateway_proto_rawDesc), len(file_api_proto_gateway_proto_rawDesc)))
	})
	return file_api_proto_gateway_proto_rawDescData
}

var file_api_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_gateway_proto_goTypes = []any{
	(*RouteRequest)(nil),  // 0: gateway.RouteRequest
	(*RouteResponse)(nil), // 1: gateway.RouteResponse
}
var file_api_proto_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.GatewayRouter.RouteMessage:input_type -> gateway.RouteRequest
	1, // 1: gateway.GatewayRouter.RouteMessage:output_type -> gateway.RouteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_gateway_proto_init() }
func file_api_proto_gateway_proto_init() {
	if File_api_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_gateway_proto_rawDesc), len(file_api_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_gateway_proto_goTypes,
		DependencyIndexes: file_api_proto_gateway_proto_depIdxs,
		MessageInfos:      file_api_proto_gateway_proto_msgTypes,
	}.Build()
	File_api_proto_gateway_proto = out.File
	file_api_proto_gateway_proto_goTypes = nil
	file_api_proto_gateway_proto_depIdxs = nil
}
